<a href="https://colab.research.google.com/github/Sudharsan1401/MyRepository/blob/main/DeepLearning%5CGreatLearning%5CRecording%5CDL_Recording_Session.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from random import choice
from numpy import array,dot,random
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

Error Back Propogation to adjust weight in output layer and hidden layer


In [2]:
def sig_act(net):
  out=1/(1+np.exp(-net))
  return out

In [6]:
#Mcculloch-Pitts Model for AND gate
w=random.rand(2)
w[0]=1
w[1]=1
train_data=[(array([0,0]),0),(array([0,1]),0),(array([1,0]),1),(array([1,1]),1)]
train_data

[(array([0, 0]), 0),
 (array([0, 1]), 0),
 (array([1, 0]), 1),
 (array([1, 1]), 1)]

In [4]:
w=

array([1., 1.])

In [7]:
act_function=lambda net : 0 if net<0.5 else 1

In [8]:
for x,_ in train_data:
  net=dot(x,w)
  print("{} : {}-> {}".format(x[:2],net,act_function(net)))

[0 0] : 0.0-> 0
[0 1] : 1.0-> 1
[1 0] : 1.0-> 1
[1 1] : 2.0-> 1


In [10]:
#Mcculoch-Pitts Model for OR gate
w=random.rand(2)
w[0]=1
w[1]=1
train_data=[(array([0,0]),0),(array([0,1]),1),(array([1,0]),1),(array([1,1]),1)]
train_data

[(array([0, 0]), 0),
 (array([0, 1]), 1),
 (array([1, 0]), 1),
 (array([1, 1]), 1)]

In [32]:
act_function= lambda net:0 if net<0.5 else 1
train_data=[(array([0,0,1]),0),(array([0,1,1]),1),
            (array([1,0,1]),1),(array([1,1,1]),1)]
random.seed(10)
w=random.rand(3)
errors=[]
eta=0.5

In [33]:
train_data

[(array([0, 0, 1]), 0),
 (array([0, 1, 1]), 1),
 (array([1, 0, 1]), 1),
 (array([1, 1, 1]), 1)]

In [34]:
w

array([0.77132064, 0.02075195, 0.63364823])

In [35]:
x,expected=choice(train_data)
print(x,expected)

[0 0 1] 0


In [36]:
dot(w,x)

0.6336482349262754

In [38]:
n=5000
for i in range(n):
  x,expected=choice(train_data)
  net=dot(w,x)
  y_pred=act_function(net)
  error=expected-y_pred
  errors.append(error)
  w+=eta*error*x

In [39]:
w

array([0.77132064, 0.52075195, 0.13364823])

In [40]:
#Testing
for x,_ in train_data:
  net=dot(x,w)
  print("{} : {}-> {}".format(x[:3],net,act_function(net)))

[0 0 1] : 0.13364823492627542-> 0
[0 1 1] : 0.6544001842856769-> 1
[1 0 1] : 0.9049688781930214-> 1
[1 1 1] : 1.4257208275524227-> 1
