<a href="https://colab.research.google.com/github/Sudharsan1401/MyRepository/blob/main/DeepLearning/GreatLearning/Recording/LAAF_Lab2_BPN_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from random import choice
from numpy import array,dot,random
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

Error Back Propagation to adjust weights in output layer and hidden layer

In [ ]:
def sig_act(net):
  out=1/(1+np.exp(-net))
  return out

In [ ]:
#X-OR (Linearly Non-separable)
random.seed(5)
w=random.rand(3,3)
train_data=[(array([0,0,1]),0),(array([0,1,1]),1),(array([1,0,1]),1),(array([1,1,1]),0)]
v=random.rand(4,1)
eta=0.01

In [ ]:
train_data

[(array([0, 0, 1]), 0),
 (array([0, 1, 1]), 1),
 (array([1, 0, 1]), 1),
 (array([1, 1, 1]), 0)]

In [ ]:
w

array([[0.22199317, 0.87073231, 0.20671916],
       [0.91861091, 0.48841119, 0.61174386],
       [0.76590786, 0.51841799, 0.2968005 ]])

In [ ]:
v

array([[0.18772123],
       [0.08074127],
       [0.7384403 ],
       [0.44130922]])

In [ ]:
x,expected=choice(train_data)
x

array([0, 1, 1])

In [ ]:
expected

1

In [ ]:
net1=dot(x,w)
net1

array([1.68451876, 1.00682918, 0.90854436])

In [ ]:
y=sig_act(net1)
y

array([0.84350196, 0.73239916, 0.7127022 ])

In [ ]:
y*(1-y)

array([0.21664445, 0.2339274 , 0.24457418])

In [ ]:
v

array([[0.18772123],
       [0.08074127],
       [0.7384403 ],
       [0.44130922]])

In [ ]:
#Hidden Layer to output layer ff flow
bias=np.array([1])
y_in=np.concatenate((y,bias),axis=0)
y_in

array([0.84350196, 0.73239916, 0.7127022 , 1.        ])

In [ ]:
net2=dot(y_in,v)
net2

array([1.18507531])

In [ ]:
y_pred=sig_act(net2)
y_pred

array([0.76585913])

In [ ]:
#Error_grad at the output layer
delta_out=(expected-y_pred)*y_pred*(1-y_pred)
delta_out

array([0.04198589])

In [ ]:
x.reshape(-1,1)

array([[0],
       [1],
       [1]])

In [ ]:
v=v+(eta*delta_out*y_in.reshape(-1,1))

In [ ]:
v

array([[0.18807538],
       [0.08104877],
       [0.73873953],
       [0.44172908]])

In [ ]:
y

array([0.87062677, 0.86733078, 0.75310909])

In [ ]:
1-y

array([0.12937323, 0.13266922, 0.24689091])

In [ ]:
y_dash=y*(1-y)
y_dash.reshape(-1,1)

array([[0.1320064 ],
       [0.19599063],
       [0.20475777]])

In [ ]:
#output side delta back propagate to hidden layer
bp=delta_out*v[:3]
bp

array([[0.00789651],
       [0.0034029 ],
       [0.03101664]])

In [ ]:
#calculating hidden layer delta
delta_hid=np.multiply(y_dash.reshape(-1,1),bp)
delta_hid

array([[0.00104239],
       [0.00066694],
       [0.0063509 ]])

In [ ]:
w

array([[0.22199317, 0.87073231, 0.20671916],
       [0.91861091, 0.48841119, 0.61174386],
       [0.76590786, 0.51841799, 0.2968005 ]])

In [ ]:
eta*delta_hid[0]

array([-0.00054931])

In [ ]:
x

array([0, 0, 1])

In [ ]:
w[:,0]=w[:,0]+(eta*delta_hid[0]*x)
w[:,1]=w[:,1]+(eta*delta_hid[1]*x)
w[:,2]=w[:,2]+(eta*delta_hid[2]*x)

In [ ]:
w

array([[0.2220105 , 0.87073835, 0.20680002],
       [0.91861091, 0.48841119, 0.61174386],
       [0.76592519, 0.51842403, 0.29688136]])

In [ ]:
choice(train_data)

(array([0, 1, 1]), 1)

In [ ]:
#XOR (linearly non-separable problem)
train_data=[(array([0,0,1]),0),(array([0,1,1]),1),(array([1,0,1]),1),(array([1,1,1]),0)]
v=random.rand(3,3) #weights connecting input to hidden layer
w=random.rand(4,1)#weights connecting hidden to output layer
eta=0.5
n=20000
#Training
for i in range(n):
  x,expected=choice(train_data)
  net1=dot(x,v)
  y=sig_act(net1) #hidden layer output
  bias=np.array([1]) #input to bias at output layer
  y_in=np.concatenate((y,bias),axis=0)
  net2=dot(y_in,w)
  y_pred=sig_act(net2) #output layer response
  delta_out=(expected-y_pred)*y_pred*(1-y_pred) #output layer error gradient
  w=w+(eta*delta_out*y_in.reshape(-1,1)) # updating the Hidden-Output weight matrix
  #Output error propagates to hidden layer
  bp=delta_out*w[:3]
  y_dash=y*(1-y)
  y_dash.reshape(-1,1)
  delta_hid=np.multiply(y_dash.reshape(-1,1),bp)
  v[:,0]=v[:,0]+(eta*delta_hid[0]*x)
  v[:,1]=v[:,1]+(eta*delta_hid[1]*x)
  v[:,2]=v[:,2]+(eta*delta_hid[2]*x)

In [ ]:
w

array([[-8.24140718],
       [ 9.64359808],
       [-6.60492572],
       [ 0.85486912]])

In [ ]:
v

array([[ 1.38811992,  6.48771971,  6.13318735],
       [ 4.89236517,  5.84318016, -3.87512628],
       [-4.08717685, -2.14029505,  1.79190016]])

In [ ]:
#train_data=[(array([0.2,0.3,1]),0),(array([0,.8,1]),1),(array([.7,0,1]),1),(array([.8,.75,1]),0)]

In [ ]:
#Testing (feedforward flow only)
for x,_ in train_data:
  net1=dot(x,v)
  y=sig_act(net1) #(3x1)
  bias=np.array([1]) #input to bias at output layer
  y_in=np.concatenate((y,bias),axis=0)
  net2=dot(y_in,w)
  y_pred=sig_act(net2)
  print("{} :-> {}".format(x[:3],y_pred))

[0 0 1] :-> [0.01930755]
[0 1 1] :-> [0.9789491]
[1 0 1] :-> [0.96279101]
[1 1 1] :-> [0.0320442]


In [ ]:
net1=dot(np.array([0,0,1]),v)
y=sig_act(net1)
y

array([0.00284162, 0.7457078 , 0.07333933])

In [ ]:
bias=np.array([1])
y_in=np.concatenate((y,bias),axis=0)
y_in

array([0.87141412, 0.93999271, 0.99994581, 1.        ])

In [ ]:
net2=dot(y_in,w)
net2

array([-3.31573648])

In [ ]:
sig_act(net2)

array([0.03503526])

In [ ]:
net1=dot(np.array([0,1,1]),v)
y=sig_act(net1)
y

array([0.19674186, 0.44697115, 0.96813193])

In [ ]:
net1=dot(np.array([1,0,1]),v)
y=sig_act(net1)
y

array([0.07308548, 0.98270977, 0.97962108])

In [ ]:
net1=dot(np.array([1,1,1]),v)
y=sig_act(net1)
y

array([0.87141412, 0.93999271, 0.99994581])

In [ ]:
hidden_neurons1=np.array([[0.00284162, 0.7457078 , 0.07333933],[0.19674186, 0.44697115, 0.96813193],[0.07308548, 0.98270977, 0.97962108],[0.87141412, 0.93999271, 0.99994581]])
hidden_neurons1

array([[0.00284162, 0.7457078 , 0.07333933],
       [0.19674186, 0.44697115, 0.96813193],
       [0.07308548, 0.98270977, 0.97962108],
       [0.87141412, 0.93999271, 0.99994581]])

In [ ]:
hidden_neurons=np.array([[0.26051543, 0.80340231, 0.41571272],[0.99086226, 0.99955096, 0.09183151],[0.97754   , 0.0706186 , 0.99405969],[0.99992536, 0.97640925, 0.95964936]])
hidden_neurons

array([[0.26051543, 0.80340231, 0.41571272],
       [0.99086226, 0.99955096, 0.09183151],
       [0.97754   , 0.0706186 , 0.99405969],
       [0.99992536, 0.97640925, 0.95964936]])

In [ ]:
input_feat=np.array([[0, 0, 1],[0, 1, 1],[1   , 0, 1],[1, 1, 1]])
input_feat

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [ ]:
import pandas as pd
HN=pd.DataFrame(hidden_neurons1,columns=['H1','H2','H3'])
HN

H1        H2        H3
0  0.002842  0.745708  0.073339
1  0.196742  0.446971  0.968132
2  0.073085  0.982710  0.979621
3  0.871414  0.939993  0.999946

In [ ]:
IP=pd.DataFrame(input_feat,columns=['X1','X2','XB'])
IP

X1  X2  XB
0   0   0   1
1   0   1   1
2   1   0   1
3   1   1   1

In [ ]:
IP['label']=['0','1','1','0']
IP

X1  X2  XB label
0   0   0   1     0
1   0   1   1     1
2   1   0   1     1
3   1   1   1     0

In [ ]:
HN['label']=['0','1','1','0']
HN

H1        H2        H3 label
0  0.002842  0.745708  0.073339     0
1  0.196742  0.446971  0.968132     1
2  0.073085  0.982710  0.979621     1
3  0.871414  0.939993  0.999946     0

In [ ]:
# 3D scatter plot
import plotly.express as px
fig = px.scatter_3d(HN, x='H1', y='H2', z='H3',color=HN.label)
fig.show()

In [ ]:
fig = px.scatter_3d(IP, x='X1', y='X2', z='XB',color=HN.label)
fig.show()

In [ ]:
v

array([[ 7.60696357],
       [-6.1595104 ],
       [-6.21165268],
       [ 1.86591419]])

In [ ]:
net2=dot(np.array([0.26051543, 0.80340231, 0.41571272,1]),v)
y_pred=sig_act(net2)
y_pred

array([0.02452618])

In [ ]:
net2=dot(np.array([0.99086226, 0.99955096, 0.09183151,1]),v)
y_pred=sig_act(net2)
y_pred

array([0.93560741])

In [ ]:
net2=dot(np.array([0.97754   , 0.0706186 , 0.99405969,1]),v)
y_pred=sig_act(net2)
y_pred

array([0.9365705])

In [ ]:
net2=dot(np.array([0.99992536, 0.97640925, 0.95964936,1]),v)
y_pred=sig_act(net2)
y_pred

array([0.07565503])